# These are supported funding model platforms

github: [ryzenPython, b33lz3bubTH]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev: souravsunju@gmail.com
custom:
  - https://souravahmed.vercel.app
  - https://www.linkedin.com/company/nrix-sas/
